# SmartCare v0.4 - Stage 4 Lab, Part D
# Appointment class as first generated by the AI pair programmer (Claude).
# Kept unchanged as evidence for the review in Part E.
# The reviewed and refactored version is in appointment.py.

from datetime import datetime
from enum import Enum

from patient import Patient
from practitioner import Practitioner
from validation import require_text


class AppointmentStatus(Enum):
    BOOKED = "Booked"
    CANCELLED = "Cancelled"
    COMPLETED = "Completed"


class InvalidStatusTransitionError(Exception):
    """Raised when an appointment is asked to make a status change that is not allowed."""


class Appointment:
    """One booking for one patient with one practitioner."""

    # Which statuses each status is allowed to change to.
    _ALLOWED_TRANSITIONS = {
        AppointmentStatus.BOOKED: {AppointmentStatus.CANCELLED, AppointmentStatus.COMPLETED},
        AppointmentStatus.CANCELLED: set(),
        AppointmentStatus.COMPLETED: set(),
    }

    def __init__(
        self,
        appointment_id: str,
        patient: Patient,
        practitioner: Practitioner,
        date_time: datetime,
        status: AppointmentStatus = AppointmentStatus.BOOKED,
    ) -> None:
        if not isinstance(patient, Patient):
            raise TypeError("patient must be a Patient")
        if not isinstance(practitioner, Practitioner):
            raise TypeError("practitioner must be a Practitioner")
        if not isinstance(date_time, datetime):
            raise TypeError("date_time must be a datetime")
        if not isinstance(status, AppointmentStatus):
            raise TypeError("status must be an AppointmentStatus")
        self._appointment_id = require_text(appointment_id, "Appointment ID")
        self._patient = patient
        self._practitioner = practitioner
        self._date_time = date_time
        self._status = status

    @property
    def appointment_id(self) -> str:
        return self._appointment_id

    @property
    def patient(self) -> Patient:
        return self._patient

    @property
    def practitioner(self) -> Practitioner:
        return self._practitioner

    @property
    def date_time(self) -> datetime:
        return self._date_time

    @property
    def status(self) -> AppointmentStatus:
        return self._status

    def is_booked(self) -> bool:
        return self._status == AppointmentStatus.BOOKED

    def _change_status(self, new_status: AppointmentStatus) -> None:
        if new_status not in self._ALLOWED_TRANSITIONS[self._status]:
            raise InvalidStatusTransitionError(
                f"Cannot change status from {self._status.value} to {new_status.value}"
            )
        self._status = new_status

    def cancel(self) -> None:
        self._change_status(AppointmentStatus.CANCELLED)

    def complete(self) -> None:
        self._change_status(AppointmentStatus.COMPLETED)

    def __repr__(self) -> str:
        return (
            f"Appointment({self._appointment_id}, {self._patient.name}, "
            f"{self._practitioner.name}, {self._date_time}, {self._status.value})"
        )
