# SmartCare v0.1 - Stage 1 Lab, Part D
# AI-generated alternative (generated by ChatGPT). Kept as the AI wrote it,
# with the same Part F tests added underneath for comparison.

appointments = []

def add_appointment(patient_name, practitioner_name, appointment_time):
    """Store one appointment in the appointments list and return it."""
    appointment = {
        "patient_name": patient_name.strip(),
        "practitioner_name": practitioner_name.strip(),
        "appointment_time": appointment_time.strip(),
    }
    appointments.append(appointment)
    return appointment


# Example use
add_appointment("Alice Smith", "Dr. John Doe", "2024-07-20 10:00 AM")
add_appointment("Bob Johnson", "Dr. Jane Roe", "2024-07-20 11:30 AM")

for appointment in appointments:
    print(appointment)


# ---------------------------------------------------------------
# Part F - Verify behaviour (same tests as smartcare_v01.py)
# ---------------------------------------------------------------

def try_booking(label, patient_name, practitioner_name, appointment_time):
    print(label)
    try:
        add_appointment(patient_name, practitioner_name, appointment_time)
        print("  Accepted")
    except Exception as error:
        print("  Rejected:", type(error).__name__, "-", error)

print()
print("Part F tests")
try_booking("Test 1: normal appointment", 'Cara Lee', 'Dr. Jane Roe', '2024-07-21 09:00 AM')
try_booking("Test 2: blank patient name", '', 'Dr. Jane Roe', '2024-07-21 10:00 AM')
try_booking("Test 3: same practitioner and time as Alice Smith", 'Dan Wu', 'Dr. John Doe', '2024-07-20 10:00 AM')
try_booking("Test 4: patient_name=None", None, 'Dr. Jane Roe', '2024-07-21 11:00 AM')
try_booking("Test 5: appointment_time=None", 'Eve Park', 'Dr. Jane Roe', None)

print()
print("Appointments after the tests")
for appointment in appointments:
    print(appointment)
